version: '3.4'

services:
    livrariamvc:
        image: ${DOCKER_REGISTRY-}livraria
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "8081:80"
        depends_on:
        - sqldata

    sqldata:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
        - SA_PASSWORD=naoSey#2022
        - ACCEPT_EULA=Y
        volumes:
        - C:\dados\volumes\mssql:/var/opt/mssql/data
        ports:
        - "1433:1433"